### ISSUE TITLE
Weird looking previous button

### ISSUE THREAD

**Issue by snehalbaghel** [julianostarek/style-mp-issuetracker#1]
![screenshot_2016-02-16-16-51-48](https://cloud.githubusercontent.com/assets/17233313/13074926/b23d695e-d4cd-11e5-8dbe-ab730d89bb4c.png)

**Comment by julianostarek** [comment]
This issue appears only on HTC Android 5.0 - 5.1 lollipop devices. Unable to fix this. If possible, update to marshmallow
